import discord
from discord.ext import commands, tasks
from discord import app_commands
import requests
import time
import json
import asyncio
import webbrowser
from pathlib import Path
import subprocess
import os
import random
import re
from typing import Optional
from datetime import datetime
import platform
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from config import (
    FIREBASE_URL,
    FIREBASE_AUTH_TOKEN,
    DISCORD_BOT_TOKEN,
    ROBLOX_API_KEY,
    ROBLOX_COOKIE,
    TEMPLATE_PLACE_ID,
    UNIVERSE_ID,
    REALGAMEID,
    BOOSTER_ROLE_ID,
    OWNER_ROLE_ID,
    MOD_ROLE_IDS
)
from spins import spin_manager, WINGS_PER_SPIN, DAILY_SPINS_NORMAL, DAILY_SPINS_BOOSTER
from gifdata_module import (
    get_random_pokemon, get_pokemon_sprite, load_gifdata, load_pokedex, load_items,
    create_sprite_sheets, get_csrf_token, get_user_id, upload_asset, grab_image_id,
    lua_to_python_dict, rebuild_gif_from_gifdata, cleanup_temp_dir, get_tier_and_emoji,
    generate_pokemon_gif, find_closest_gifdata_match,
    COOKIE_FILE, TEMP_DIR, ensure_temp_dir
)

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix='!', intents=intents, help_command=None)

MAIN_GAME_FILE = Path("maingame.json")
GAME_FILE_DIR = Path("directory/game-file")
TEMP_PLACES_DIR = Path("temp_places")

class RobloxAPIKeyManager:
    def __init__(self):
        self.chrome_options = Options()
        self.chrome_options.add_argument('--headless')
        self.chrome_options.add_argument('--no-sandbox')
        self.chrome_options.add_argument('--disable-dev-shm-usage')
        self.chrome_options.add_argument('--disable-gpu')
    
    async def create_api_key(self, cookie, universe_id, place_id):
        driver = None
        try:
            driver = webdriver.Chrome(options=self.chrome_options)
            driver.get("https://www.roblox.com")
            
            driver.add_cookie({
                'name': '.ROBLOSECURITY',
                'value': cookie,
                'domain': '.roblox.com'
            })
            
            await asyncio.sleep(2)
            driver.get(f"https://create.roblox.com/credentials")
            
            await asyncio.sleep(3)
            
            create_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.XPATH, "//button[contains(text(), 'Create API Key')]"))
            )
            create_button.click()
            
            await asyncio.sleep(2)
            
            name_input = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "//input[@placeholder='API Key Name']"))
            )
            name_input.send_keys(f"AutoGenerated-Place{place_id}")
            
            await asyncio.sleep(1)
            
            experience_dropdown = driver.find_element(By.XPATH, "//select[@aria-label='Select Experience']")
            experience_dropdown.click()
            await asyncio.sleep(1)
            
            experience_option = driver.find_element(By.XPATH, f"//option[@value='{universe_id}']")
            experience_option.click()
            
            await asyncio.sleep(1)
            
            permissions_checkboxes = driver.find_elements(By.XPATH, "//input[@type='checkbox']")
            for checkbox in permissions_checkboxes:
                permission_name = checkbox.get_attribute('name')
                if permission_name and any(perm in permission_name.lower() for perm in ['place', 'write', 'asset', 'audio']):
                    if not checkbox.is_selected():
                        checkbox.click()
            
            await asyncio.sleep(1)
            
            create_key_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Create')]")
            create_key_button.click()
            
            await asyncio.sleep(3)
            
            api_key_element = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "//input[@type='password']"))
            )
            api_key = api_key_element.get_attribute('value')
            
            show_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Show')]")
            show_button.click()
            await asyncio.sleep(1)
            
            api_key = api_key_element.get_attribute('value')
            
            return {
                'success': True,
                'api_key': api_key,
                'name': f"AutoGenerated-Place{place_id}"
            }
            
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }
        finally:
            if driver:
                driver.quit()
    
    async def create_api_key_for_backup(self, cookie, universe_id, backup_place_id):
        """Create API key with place publishing permissions for backup place"""
        driver = None
        try:
            driver = webdriver.Chrome(options=self.chrome_options)
            driver.get("https://www.roblox.com")
            
            driver.add_cookie({
                'name': '.ROBLOSECURITY',
                'value': cookie,
                'domain': '.roblox.com'
            })
            
            await asyncio.sleep(2)
            driver.get(f"https://create.roblox.com/credentials")
            
            await asyncio.sleep(3)
            
            create_button = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.XPATH, "//button[contains(text(), 'Create API Key')]"))
            )
            create_button.click()
            
            await asyncio.sleep(2)
            
            name_input = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "//input[@placeholder='API Key Name']"))
            )
            name_input.send_keys(f"AutoRestore-Backup{backup_place_id}")
            
            await asyncio.sleep(1)
            
            experience_dropdown = driver.find_element(By.XPATH, "//select[@aria-label='Select Experience']")
            experience_dropdown.click()
            await asyncio.sleep(1)
            
            experience_option = driver.find_element(By.XPATH, f"//option[@value='{universe_id}']")
            experience_option.click()
            
            await asyncio.sleep(1)
            
            # Select place publishing permissions
            permissions_checkboxes = driver.find_elements(By.XPATH, "//input[@type='checkbox']")
            for checkbox in permissions_checkboxes:
                permission_name = checkbox.get_attribute('name')
                if permission_name and any(perm in permission_name.lower() for perm in ['place', 'publish', 'write']):
                    if not checkbox.is_selected():
                        checkbox.click()
            
            await asyncio.sleep(1)
            
            create_key_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Create')]")
            create_key_button.click()
            
            await asyncio.sleep(3)
            
            api_key_element = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.XPATH, "//input[@type='password']"))
            )
            api_key = api_key_element.get_attribute('value')
            
            show_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Show')]")
            show_button.click()
            await asyncio.sleep(1)
            
            api_key = api_key_element.get_attribute('value')
            
            return {
                'success': True,
                'api_key': api_key,
                'name': f"AutoRestore-Backup{backup_place_id}"
            }
            
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }
        finally:
            if driver:
                driver.quit()

class RobloxBackupManager:
    def __init__(self):
        self.firebase_url = FIREBASE_URL
        self.auth_token = FIREBASE_AUTH_TOKEN
        self.roblox_cookie = ROBLOX_COOKIE
        self.template_place_id = TEMPLATE_PLACE_ID
    
    def get_place_info(self, place_id):
        try:
            response = requests.get(
                f"https://games.roblox.com/v1/games/multiget-place-details?placeIds={place_id}"
            )
            if response.status_code == 200:
                data = response.json()
                if data and len(data) > 0:
                    place = data[0]
                    return {
                        "name": place.get("name", "Backup Place"),
                        "description": place.get("description", "")
                    }
        except Exception as e:
            print(f"Error getting place info: {e}")
        return {"name": "Backup Place", "description": ""}
    
    def send_command_to_lua(self, place_info):
        try:
            data = {
                "command": "clone",
                "placeName": place_info["name"],
                "placeDescription": place_info["description"],
                "templatePlaceId": self.template_place_id,
                "timestamp": time.time()
            }
            response = requests.put(
                f"{self.firebase_url}/command.json?auth={self.auth_token}",
                data=json.dumps(data),
                headers={"Content-Type": "application/json"}
            )
            return response.status_code == 200
        except Exception as e:
            print(f"Error sending command: {e}")
            return False
    
    async def wait_for_lua_response(self, timeout=60):
        start_time = time.time()
        
        while time.time() - start_time < timeout:
            try:
                response = requests.get(f"{self.firebase_url}/response.json?auth={self.auth_token}")
                if response.status_code == 200:
                    data = response.json()
                    if data and "backupKey" in data:
                        return data["backupKey"]
            except Exception as e:
                print(f"Error checking response: {e}")
            
            await asyncio.sleep(2)
        
        return None
    
    def update_backup(self, backup_key):
        try:
            response = requests.put(
                f"{self.firebase_url}/backup.json?auth={self.auth_token}",
                data=json.dumps(backup_key),
                headers={"Content-Type": "application/json"}
            )
            return response.status_code == 200
        except Exception as e:
            print(f"Error updating backup: {e}")
            return False
    
    def cleanup_firebase(self):
        try:
            requests.delete(f"{self.firebase_url}/command.json?auth={self.auth_token}")
            requests.delete(f"{self.firebase_url}/response.json?auth={self.auth_token}")
        except Exception as e:
            print(f"Error cleaning up: {e}")
    
    def get_current_backup(self):
        try:
            response = requests.get(f"{self.firebase_url}/backup.json?auth={self.auth_token}")
            if response.status_code == 200:
                data = response.json()
                if isinstance(data, (int, float)):
                    return int(data)
        except Exception as e:
            print(f"Error getting backup: {e}")
        return None
    
    def set_taken_down_flag(self, is_down):
        """Set TakenDown flag in Firebase"""
        try:
            response = requests.put(
                f"{self.firebase_url}/TakenDown.json?auth={self.auth_token}",
                data=json.dumps(is_down),
                headers={"Content-Type": "application/json"}
            )
            status = "true" if is_down else "false"
            print(f"✅ Set TakenDown to {status} in Firebase")
            return response.status_code == 200
        except Exception as e:
            print(f"Error setting TakenDown flag: {e}")
            return False
    
    def set_realgameid(self, place_id):
        """Store REALGAMEID in Firebase"""
        try:
            response = requests.put(
                f"{self.firebase_url}/REALGAMEID.json?auth={self.auth_token}",
                data=json.dumps(place_id),
                headers={"Content-Type": "application/json"}
            )
            print(f"✅ Stored REALGAMEID {place_id} in Firebase")
            return response.status_code == 200
        except Exception as e:
            print(f"Error setting REALGAMEID: {e}")
            return False
    
    def join_roblox_game(self):
        game_url = f"roblox://placeId={self.template_place_id}"
        try:
            print(f"🎮 Attempting to join Roblox game: {game_url}")
            
            system = platform.system()
            if system == "Windows":
                # Hide window on Windows
                startupinfo = subprocess.STARTUPINFO()
                startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
                startupinfo.wShowWindow = subprocess.SW_HIDE
                subprocess.Popen(
                    ['cmd', '/c', f'start {game_url}'],
                    startupinfo=startupinfo,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL
                )
            elif system == "Darwin":  # macOS
                # Open in background on macOS
                subprocess.Popen(
                    ['open', '-g', game_url],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    preexec_fn=lambda: None if sys.platform == 'win32' else os.setsid()
                )
            else:  # Linux
                subprocess.Popen(
                    ['xdg-open', game_url],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    start_new_session=True
                )
            
            print(f"✅ Game join command sent (hidden)")
        except Exception as e:
            print(f"❌ Failed to join Roblox game: {e}")

class PlacePublisher:
    def __init__(self):
        self.api_key = ROBLOX_API_KEY
        self.universe_id = UNIVERSE_ID
        self.publish_endpoint = f"https://apis.roblox.com/universes/v1/{self.universe_id}/places"
    
    async def publish_place(self, place_id, file_path):
        if not Path(file_path).exists():
            raise Exception(f"Place file not found: {file_path}")
        
        file_ext = Path(file_path).suffix.lower()
        if file_ext not in ['.rbxl', '.rbxlx']:
            raise Exception(f"Invalid file format: {file_ext}. Expected .rbxl or .rbxlx")
        
        file_size = Path(file_path).stat().st_size
        if file_size > 100 * 1024 * 1024:
            raise Exception("File size exceeds 100MB limit")
        
        try:
            with open(file_path, 'rb') as f:
                file_content = f.read()
            
            headers = {
                "x-api-key": self.api_key,
                "Content-Type": "application/octet-stream"
            }
            
            url = f"{self.publish_endpoint}/{place_id}/versions"
            
            request_payload = {
                "versionType": "Published"
            }
            
            files = {
                'request': (None, json.dumps(request_payload), 'application/json'),
                'fileContent': (Path(file_path).name, file_content, 'application/octet-stream')
            }
            
            headers_multipart = {
                "x-api-key": self.api_key
            }
            
            response = requests.post(
                url,
                headers=headers_multipart,
                files=files,
                timeout=60
            )
            
            if response.status_code == 200:
                result = response.json()
                return {
                    'success': True,
                    'versionNumber': result.get('versionNumber'),
                    'data': result
                }
            
            raise Exception(f"Publishing failed: {response.status_code} - {response.text}")
            
        except Exception as e:
            raise Exception(f"Publish error: {str(e)}")

class AudioUploader:
    def __init__(self):
        self.api_key = ROBLOX_API_KEY
        self.upload_endpoint = "https://apis.roblox.com/assets/v1/assets"
        self.supported_formats = ['.mp3', '.ogg', '.wav', '.flac']
    
    def convert_mp3_to_ogg(self, mp3_path):
        try:
            output_dir = Path(mp3_path).parent / 'converted'
            output_dir.mkdir(exist_ok=True)
            
            ogg_path = output_dir / f"{Path(mp3_path).stem}.ogg"
            
            if ogg_path.exists():
                return str(ogg_path)
            
            result = subprocess.run(
                ['ffmpeg', '-i', mp3_path, '-c:a', 'libvorbis', '-y', str(ogg_path)],
                capture_output=True,
                timeout=30
            )
            
            if result.returncode == 0 and ogg_path.exists():
                return str(ogg_path)
            else:
                return mp3_path
                
        except Exception as e:
            print(f"Conversion error: {e}")
            return mp3_path
    
    async def upload_audio(self, file_path, display_name, description="", creator_id=None, is_group=False):
        if not Path(file_path).exists():
            raise Exception(f"File not found: {file_path}")
        
        if creator_id is None:
            raise Exception("Creator ID is required")
        
        file_ext = Path(file_path).suffix.lower()
        if file_ext not in self.supported_formats:
            raise Exception(f"Unsupported format: {file_ext}")
        
        file_size = Path(file_path).stat().st_size
        if file_size > 20 * 1024 * 1024:
            raise Exception("File size exceeds 20MB limit")
        
        upload_path = file_path
        converted = False
        
        if file_ext == '.mp3':
            try:
                upload_path = self.convert_mp3_to_ogg(file_path)
                if upload_path != file_path:
                    converted = True
                    file_ext = '.ogg'
            except Exception as e:
                print(f"Conversion failed, using original: {e}")
        
        request_data = {
            "assetType": "Audio",
            "displayName": display_name,
            "description": description
        }
        
        if is_group:
            request_data["creationContext"] = {"creator": {"groupId": int(creator_id)}}
        else:
            request_data["creationContext"] = {"creator": {"userId": int(creator_id)}}
        
        try:
            with open(upload_path, 'rb') as f:
                files = {
                    'request': (None, json.dumps(request_data), 'application/json'),
                    'fileContent': (Path(file_path).name, f, self._get_mime_type(file_ext))
                }
                
                headers = {"x-api-key": self.api_key}
                
                response = requests.post(
                    self.upload_endpoint,
                    headers=headers,
                    files=files,
                    timeout=30
                )
            
            if response.status_code == 200:
                result = response.json()
                
                if 'operationId' in result:
                    final_result = await self._poll_operation(result['operationId'])
                    if final_result:
                        asset_id = final_result.get('assetId') or final_result.get('id')
                        return {
                            'success': True,
                            'assetId': asset_id,
                            'converted': converted,
                            'data': final_result
                        }
                else:
                    asset_id = result.get('assetId') or result.get('id')
                    return {
                        'success': True,
                        'assetId': asset_id,
                        'converted': converted,
                        'data': result
                    }
            
            raise Exception(f"Upload failed: {response.status_code} - {response.text}")
            
        except Exception as e:
            raise Exception(f"Upload error: {str(e)}")
    
    async def _poll_operation(self, operation_id, timeout=60):
        url = f"https://apis.roblox.com/assets/v1/operations/{operation_id}"
        headers = {"x-api-key": self.api_key}
        
        start = time.time()
        while time.time() - start < timeout:
            await asyncio.sleep(2)
            
            try:
                response = requests.get(url, headers=headers, timeout=10)
                if response.status_code == 200:
                    data = response.json()
                    if data.get('done'):
                        if 'response' in data:
                            return data['response']
                        elif 'error' in data:
                            raise Exception(f"Operation failed: {data['error']}")
                        return data
            except Exception as e:
                print(f"Poll error: {e}")
        
        return None
    
    def _get_mime_type(self, ext):
        mime_types = {
            '.mp3': 'audio/mpeg',
            '.ogg': 'audio/ogg',
            '.wav': 'audio/wav',
            '.flac': 'audio/flac'
        }
        return mime_types.get(ext, 'audio/mpeg')

api_key_manager = RobloxAPIKeyManager()
manager = RobloxBackupManager()
place_publisher = PlacePublisher()
audio_uploader = AudioUploader()

class GameMonitor:
    def __init__(self):
        self.main_game_id = None
        self.monitoring = False
        self.upload_channel = None
        self.pending_file = None
        self.file_wait_time = None
        self.realgame_monitoring = False
        self.realgame_channel = None
        self.last_visit_milestone = 0
        self.load_main_game()
    
    def load_main_game(self):
        if MAIN_GAME_FILE.exists():
            try:
                with open(MAIN_GAME_FILE, 'r') as f:
                    data = json.load(f)
                    self.main_game_id = data.get('place_id')
            except:
                self.main_game_id = None
    
    def save_main_game(self, place_id):
        self.main_game_id = place_id
        with open(MAIN_GAME_FILE, 'w') as f:
            json.dump({'place_id': place_id}, f)
    
    async def check_game_status(self, channel):
        if not self.main_game_id:
            return
        
        url = f"https://www.roblox.com/games/{self.main_game_id}"
        try:
            response = requests.head(url, allow_redirects=False, timeout=5)
            
            if response.status_code == 404 or (response.status_code >= 300 and response.status_code < 400):
                await self.handle_404(channel, url)
        except:
            await self.handle_404(channel, url)
    
    async def check_realgame_status(self, channel):
        """Check status of REALGAMEID and auto-restore if 404"""
        if not REALGAMEID or REALGAMEID == 0:
            return
        
        url = f"https://www.roblox.com/games/{REALGAMEID}"
        try:
            response = requests.head(url, allow_redirects=False, timeout=5)
            
            if response.status_code == 404:
                await self.handle_realgame_404(channel, url)
            elif response.status_code == 200:
                # Check for visit milestones
                await self.check_visit_milestone()
        except Exception as e:
            print(f"Error checking REALGAMEID status: {e}")
    
    async def check_visit_milestone(self):
        """Check if game hits 1000 visit increments and upload to backup"""
        try:
            # Get current visit count
            response = requests.get(
                f"https://games.roblox.com/v1/games?universeIds={UNIVERSE_ID}",
                timeout=5
            )
            
            if response.status_code != 200:
                return
            
            games_data = response.json().get("data", [])
            if not games_data:
                return
            
            current_visits = games_data[0].get("visits", 0)
            current_milestone = current_visits // 1000
            
            # If we've hit a new milestone, upload to backup
            if current_milestone > self.last_visit_milestone:
                self.last_visit_milestone = current_milestone
                await self.upload_milestone_backup()
        
        except Exception:
            pass
    
    async def upload_milestone_backup(self):
        """Silently upload .rbxl to backup place when visit milestone is hit"""
        try:
            # Get backup place ID
            backup_place_id = manager.get_current_backup()
            if not backup_place_id:
                return
            
            # Get .rbxl file from temp_places
            TEMP_PLACES_DIR.mkdir(exist_ok=True)
            rbxl_files = list(TEMP_PLACES_DIR.glob("*.rbxl")) + list(TEMP_PLACES_DIR.glob("*.rbxlx"))
            
            if not rbxl_files:
                return
            
            game_file = rbxl_files[0]
            
            # Create API key
            if not ROBLOX_COOKIE:
                return
            
            api_key_result = await api_key_manager.create_api_key_for_backup(
                ROBLOX_COOKIE, UNIVERSE_ID, backup_place_id
            )
            
            if not api_key_result['success']:
                return
            
            # Upload to backup
            temp_publisher = PlacePublisher()
            temp_publisher.api_key = api_key_result['api_key']
            await temp_publisher.publish_place(backup_place_id, str(game_file))
        
        except:
            pass
    
    async def handle_realgame_404(self, channel, url):
        """Confirm 404 via Selenium and trigger auto-restore"""
        print(f"🚨 REALGAMEID {REALGAMEID} detected as down! Confirming with Selenium...")
        
        driver = None
        try:
            chrome_options = Options()
            chrome_options.add_argument('--headless')
            chrome_options.add_argument('--no-sandbox')
            chrome_options.add_argument('--disable-dev-shm-usage')
            driver = webdriver.Chrome(options=chrome_options)
            driver.get(url)
            
            final_url = driver.current_url
            if '404' in final_url:
                print(f"✅ Confirmed 404 error for REALGAMEID - starting auto-restore")
                # Set TakenDown flag to true in Firebase
                manager.set_taken_down_flag(True)
                await self.trigger_realgame_auto_restore(channel)
        finally:
            if driver:
                driver.quit()
    
    async def trigger_realgame_auto_restore(self, channel):
        """Auto-restore REALGAMEID using rbxl from temp_places and generated API key"""
        print(f"🚀 Starting REALGAMEID auto-restore workflow...")
        
        embed = discord.Embed(
            title="🚨 REALGAMEID Detected as Down!",
            description="Starting automatic restoration...",
            color=discord.Color.orange()
        )
        embed.add_field(name="Place ID", value=str(REALGAMEID), inline=False)
        embed.add_field(name="Status", value="Getting backup place and rbxl file...", inline=False)
        status_msg = await channel.send(embed=embed)
        
        try:
            # Get backup place ID from Firebase
            embed.description = "Step 1/4: Getting backup place ID from Firebase..."
            await status_msg.edit(embed=embed)
            
            backup_place_id = manager.get_current_backup()
            if not backup_place_id:
                raise Exception("No backup place ID found in Firebase")
            
            print(f"✅ Backup place ID: {backup_place_id}")
            
            # Get rbxl file from temp_places
            embed.description = "Step 2/4: Looking for rbxl file in temp_places..."
            await status_msg.edit(embed=embed)
            
            TEMP_PLACES_DIR.mkdir(exist_ok=True)
            rbxl_files = list(TEMP_PLACES_DIR.glob("*.rbxl")) + list(TEMP_PLACES_DIR.glob("*.rbxlx"))
            
            if not rbxl_files:
                raise Exception("No .rbxl or .rbxlx file found in temp_places/")
            
            game_file = rbxl_files[0]
            print(f"✅ Found game file: {game_file.name}")
            
            # Create API key with place publishing permissions
            embed.description = "Step 3/4: Creating API key with place publishing permissions..."
            await status_msg.edit(embed=embed)
            
            if not ROBLOX_COOKIE:
                raise Exception("ROBLOX_COOKIE not configured. Cannot generate API key.")
            
            api_key_result = await api_key_manager.create_api_key_for_backup(
                ROBLOX_COOKIE, UNIVERSE_ID, backup_place_id
            )
            
            if not api_key_result['success']:
                raise Exception(f"Failed to create API key: {api_key_result.get('error', 'Unknown error')}")
            
            api_key = api_key_result['api_key']
            print(f"✅ API key created: {api_key_result['name']}")
            
            # Publish rbxl to backup place using the new API key
            embed.description = "Step 4/4: Publishing game file to backup place..."
            await status_msg.edit(embed=embed)
            
            # Create temporary publisher with the new API key
            temp_publisher = PlacePublisher()
            temp_publisher.api_key = api_key
            
            result = await temp_publisher.publish_place(backup_place_id, str(game_file))
            
            print(f"✅ Game file published successfully!")
            
            # Store REALGAMEID and set TakenDown to false in Firebase
            manager.set_realgameid(REALGAMEID)
            manager.set_taken_down_flag(False)
            
            embed = discord.Embed(
                title="✅ REALGAMEID Auto-Restored Successfully!",
                color=discord.Color.green()
            )
            embed.add_field(name="Original Place ID", value=str(REALGAMEID), inline=True)
            embed.add_field(name="Backup Place ID", value=str(backup_place_id), inline=True)
            embed.add_field(name="Version", value=str(result.get('versionNumber', 'N/A')), inline=True)
            embed.add_field(
                name="Play Game",
                value=f"https://www.roblox.com/games/{backup_place_id}",
                inline=False
            )
            embed.add_field(
                name="File Used",
                value=game_file.name,
                inline=False
            )
            await status_msg.edit(embed=embed)
            
        except Exception as e:
            print(f"❌ Auto-restore failed: {str(e)}")
            embed = discord.Embed(
                title="❌ REALGAMEID Auto-Restore Failed",
                description=f"Error: {str(e)}",
                color=discord.Color.red()
            )
            await status_msg.edit(embed=embed)
    
    async def handle_404(self, channel, url):
        print(f"🚨 Game {self.main_game_id} detected as down! Starting restoration...")
        
        driver = None
        try:
            chrome_options = Options()
            chrome_options.add_argument('--headless')
            chrome_options.add_argument('--no-sandbox')
            chrome_options.add_argument('--disable-dev-shm-usage')
            driver = webdriver.Chrome(options=chrome_options)
            driver.get(url)
            
            final_url = driver.current_url
            if '404' in final_url:
                print(f"✅ Confirmed 404 error - starting auto-restore")
                await self.trigger_auto_restore(channel)
        finally:
            if driver:
                driver.quit()
    
    async def trigger_auto_restore(self, channel):
        embed = discord.Embed(
            title="🚨 Game Detected as Down!",
            description="Starting automatic restoration...",
            color=discord.Color.orange()
        )
        embed.add_field(name="Place ID", value=str(self.main_game_id), inline=False)
        embed.add_field(name="Status", value="Waiting for game file (.rbxl)...", inline=False)
        embed.add_field(name="Timeout", value="30 seconds", inline=False)
        status_msg = await channel.send(embed=embed)
        
        self.upload_channel = channel
        self.file_wait_time = time.time()
        self.pending_file = None
        
        await asyncio.sleep(30)
        
        game_file = self.pending_file
        if not game_file:
            game_file = await self.find_game_file()
        
        if not game_file:
            embed.description = "❌ No game file provided or found in directory/game-file"
            await status_msg.edit(embed=embed)
            return
        
        await self.run_auto_restore(status_msg, game_file)
    
    async def find_game_file(self):
        if not GAME_FILE_DIR.exists():
            return None
        
        files = list(GAME_FILE_DIR.glob("*.rbxl")) + list(GAME_FILE_DIR.glob("*.rbxlx"))
        if files:
            return files[0]
        return None
    
    async def run_auto_restore(self, status_msg, game_file):
        try:
            embed = discord.Embed(
                title="🎮 Auto-Restoring Game",
                description="Step 1/3: Creating backup...",
                color=discord.Color.blue()
            )
            await status_msg.edit(embed=embed)
            
            place_info = manager.get_place_info(manager.template_place_id)
            manager.cleanup_firebase()
            
            embed.description = f"Step 1/3: Creating backup...\n**Place:** {place_info['name']}"
            await status_msg.edit(embed=embed)
            
            manager.join_roblox_game()
            await asyncio.sleep(15)
            
            embed.description = f"Step 1/3: Waiting for clone...\n**Place:** {place_info['name']}"
            await status_msg.edit(embed=embed)
            
            if not manager.send_command_to_lua(place_info):
                raise Exception("Failed to send clone command")
            
            backup_key = await manager.wait_for_lua_response()
            if not backup_key:
                raise Exception("No response from Lua script")
            
            if not manager.update_backup(backup_key):
                raise Exception("Failed to update backup")
            
            embed.description = f"Step 2/3: Uploading game file...\n**Backup Place ID:** {backup_key}"
            await status_msg.edit(embed=embed)
            
            embed.description = f"Step 3/3: Publishing to backup place...\n**Backup Place ID:** {backup_key}"
            await status_msg.edit(embed=embed)
            
            result = await place_publisher.publish_place(backup_key, str(game_file))
            
            embed = discord.Embed(
                title="✅ Game Restored Successfully!",
                color=discord.Color.green()
            )
            embed.add_field(name="Original Place", value=str(self.main_game_id), inline=True)
            embed.add_field(name="Backup Place", value=str(backup_key), inline=True)
            embed.add_field(name="Version", value=str(result.get('versionNumber', 'N/A')), inline=True)
            embed.add_field(
                name="Play Game",
                value=f"https://www.roblox.com/games/{backup_key}",
                inline=False
            )
            await status_msg.edit(embed=embed)
            manager.cleanup_firebase()
            
        except Exception as e:
            embed = discord.Embed(
                title="❌ Auto-Restore Failed",
                description=f"Error: {str(e)}",
                color=discord.Color.red()
            )
            await status_msg.edit(embed=embed)
            manager.cleanup_firebase()

game_monitor = GameMonitor()

@bot.event
async def on_ready():
    print(f'✅ Bot logged in as {bot.user}')
    print(f'📊 Connected to {len(bot.guilds)} server(s)')
    await bot.tree.sync()
    if not monitor_game_status.is_running():
        monitor_game_status.start()
    if not monitor_realgame_status.is_running():
        monitor_realgame_status.start()
    if not periodic_backup.is_running():
        periodic_backup.start()

@tasks.loop(seconds=3)
async def monitor_game_status():
    if game_monitor.main_game_id:
        channel = None
        for guild in bot.guilds:
            for ch in guild.text_channels:
                if ch.name == 'general' or ch.permissions_for(guild.me).send_messages:
                    channel = ch
                    break
            if channel:
                break
        
        if channel:
            await game_monitor.check_game_status(channel)

@tasks.loop(seconds=3)
async def monitor_realgame_status():
    if REALGAMEID and REALGAMEID != 0:
        channel = None
        for guild in bot.guilds:
            for ch in guild.text_channels:
                if ch.name == 'general' or ch.permissions_for(guild.me).send_messages:
                    channel = ch
                    break
            if channel:
                break
        
        if channel:
            await game_monitor.check_realgame_status(channel)

@tasks.loop(minutes=5)
async def periodic_backup():
    """Back up the game every 5 minutes"""
    if not TEMPLATE_PLACE_ID or TEMPLATE_PLACE_ID == 0:
        return
    
    try:
        print(f"🔄 [5-MIN BACKUP] Starting periodic backup at {datetime.utcnow().isoformat()}")
        place_info = manager.get_place_info(manager.template_place_id)
        manager.cleanup_firebase()
        
        print(f"🎮 [5-MIN BACKUP] Joining game (Place: {manager.template_place_id})")
        manager.join_roblox_game()
        await asyncio.sleep(15)
        
        print(f"📤 [5-MIN BACKUP] Sending clone command to Lua")
        if not manager.send_command_to_lua(place_info):
            print(f"❌ [5-MIN BACKUP] Failed to send command")
            return
        
        print(f"⏳ [5-MIN BACKUP] Waiting for Lua response...")
        backup_key = await manager.wait_for_lua_response(timeout=90)
        
        if not backup_key:
            print(f"❌ [5-MIN BACKUP] No response from Lua script")
            return
        
        print(f"💾 [5-MIN BACKUP] Updating backup with ID: {backup_key}")
        manager.update_backup(backup_key)
        print(f"✅ [5-MIN BACKUP] Backup completed successfully!")
        
    except Exception as e:
        print(f"❌ [5-MIN BACKUP] Error: {e}")

@bot.tree.command(name="backup", description="Create a new backup of the Roblox place")
async def create_backup(interaction: discord.Interaction):
    """Create a new backup of the Roblox place"""
    await interaction.response.defer()
    embed = discord.Embed(
        title="🔄 Creating Backup",
        description="Starting backup process...",
        color=discord.Color.blue()
    )
    status_msg = await interaction.followup.send(embed=embed)
    
    try:
        embed.description = "Fetching place information..."
        await status_msg.edit(embed=embed)
        
        place_info = manager.get_place_info(manager.template_place_id)
        manager.cleanup_firebase()
        
        embed.description = f"Joining Roblox game...\n**Place:** {place_info['name']}"
        await status_msg.edit(embed=embed)
        
        manager.join_roblox_game()
        await asyncio.sleep(15)
        
        embed.description = "Sending clone command to Lua script..."
        await status_msg.edit(embed=embed)
        
        if not manager.send_command_to_lua(place_info):
            raise Exception("Failed to send command")
        
        embed.description = "Waiting for Lua script response..."
        await status_msg.edit(embed=embed)
        
        backup_key = await manager.wait_for_lua_response()
        
        if not backup_key:
            raise Exception("No response from Lua script")
        
        embed.description = f"Updating backup with Place ID: {backup_key}"
        await status_msg.edit(embed=embed)
        
        if not manager.update_backup(backup_key):
            raise Exception("Failed to update backup")
        
        embed = discord.Embed(
            title="✅ Backup Created Successfully",
            color=discord.Color.green()
        )
        embed.add_field(name="Place Name", value=place_info['name'], inline=False)
        embed.add_field(name="New Backup ID", value=str(backup_key), inline=False)
        embed.add_field(name="Template ID", value=str(manager.template_place_id), inline=False)
        embed.set_footer(text=f"Requested by {interaction.user}")
        
        await status_msg.edit(embed=embed)
        manager.cleanup_firebase()
        
    except Exception as e:
        embed = discord.Embed(
            title="❌ Backup Failed",
            description=f"Error: {str(e)}",
            color=discord.Color.red()
        )
        embed.set_footer(text=f"Requested by {interaction.user}")
        await status_msg.edit(embed=embed)
        manager.cleanup_firebase()

@bot.tree.command(name="upload", description="Upload audio file to Roblox")
@app_commands.describe(creator_id="User ID or g:GroupID", display_name="Display name for audio", description="Description for audio", file="Audio file (MP3/OGG/WAV/FLAC)")
async def upload_audio(interaction: discord.Interaction, creator_id: str, display_name: str, file: discord.Attachment, description: str = ""):
    """Upload audio file to Roblox"""
    await interaction.response.defer()
    
    file_ext = Path(file.filename).suffix.lower()
    
    if file_ext not in ['.mp3', '.ogg', '.wav', '.flac']:
        await interaction.followup.send(f"❌ Unsupported format: {file_ext}\nSupported: .mp3, .ogg, .wav, .flac")
        return
    
    embed = discord.Embed(
        title="🎵 Uploading Audio",
        description=f"Downloading {file.filename}...",
        color=discord.Color.blue()
    )
    status_msg = await interaction.followup.send(embed=embed)
    
    file_path = None
    try:
        temp_dir = Path("temp_audio")
        temp_dir.mkdir(exist_ok=True)
        file_path = temp_dir / file.filename
        
        await file.save(file_path)
        
        is_group = creator_id.startswith('g:')
        if is_group:
            creator_id = creator_id[2:]
        
        embed.description = "Uploading to Roblox..."
        await status_msg.edit(embed=embed)
        
        result = await audio_uploader.upload_audio(
            str(file_path),
            display_name,
            description,
            creator_id,
            is_group
        )
        
        file_path.unlink()
        
        embed = discord.Embed(
            title="✅ Audio Uploaded Successfully",
            color=discord.Color.green()
        )
        embed.add_field(name="File", value=file.filename, inline=True)
        embed.add_field(name="Display Name", value=display_name, inline=True)
        embed.add_field(name="Asset ID", value=str(result['assetId']), inline=False)
        
        if result['converted']:
            embed.add_field(name="Conversion", value="MP3 → OGG", inline=True)
        
        embed.add_field(
            name="Roblox Link",
            value=f"https://www.roblox.com/library/{result['assetId']}",
            inline=False
        )
        embed.set_footer(text=f"Uploaded by {interaction.user}")
        
        await status_msg.edit(embed=embed)
        
    except Exception as e:
        embed = discord.Embed(
            title="❌ Upload Failed",
            description=f"Error: {str(e)}",
            color=discord.Color.red()
        )
        embed.set_footer(text=f"Requested by {interaction.user}")
        await status_msg.edit(embed=embed)
        
        if file_path and file_path.exists():
            file_path.unlink()

@bot.tree.command(name="checkbackup", description="Check the current backup place ID")
async def check_backup(interaction: discord.Interaction):
    """Check the current backup place ID"""
    await interaction.response.defer()
    backup_id = manager.get_current_backup()
    
    if backup_id:
        embed = discord.Embed(
            title="📋 Current Backup",
            description=f"**Place ID:** {backup_id}",
            color=discord.Color.blue()
        )
        embed.add_field(
            name="Roblox Link",
            value=f"https://www.roblox.com/games/{backup_id}",
            inline=False
        )
    else:
        embed = discord.Embed(
            title="❌ No Backup Found",
            description="No backup place ID is currently set.",
            color=discord.Color.red()
        )
    
    embed.set_footer(text=f"Requested by {interaction.user}")
    await interaction.followup.send(embed=embed)

@bot.tree.command(name="settemplate", description="Set the template place ID (Admin only)")
@app_commands.describe(place_id="Roblox place ID")
@app_commands.checks.has_permissions(administrator=True)
async def set_template(interaction: discord.Interaction, place_id: int):
    """Set the template place ID (Admin only)"""
    await interaction.response.defer()
    manager.template_place_id = place_id
    
    embed = discord.Embed(
        title="✅ Template Updated",
        description=f"Template Place ID set to: **{place_id}**",
        color=discord.Color.green()
    )
    embed.set_footer(text=f"Updated by {interaction.user}")
    await interaction.followup.send(embed=embed)

@bot.tree.command(name="publish", description="Publish a .rbxl file to a Roblox place")
@app_commands.describe(place_id="Roblox place ID", file="Place file (.rbxl or .rbxlx)")
async def publish_place(interaction: discord.Interaction, place_id: int, file: discord.Attachment):
    """Publish a .rbxl file to a Roblox place"""
    await interaction.response.defer()
    
    file_ext = Path(file.filename).suffix.lower()
    
    if file_ext not in ['.rbxl', '.rbxlx']:
        await interaction.followup.send(f"❌ Invalid file format: {file_ext}\nSupported: .rbxl, .rbxlx")
        return
    
    embed = discord.Embed(
        title="📤 Publishing Place",
        description=f"Downloading {file.filename}...",
        color=discord.Color.blue()
    )
    status_msg = await interaction.followup.send(embed=embed)
    
    file_path = None
    try:
        temp_dir = Path("temp_places")
        temp_dir.mkdir(exist_ok=True)
        file_path = temp_dir / file.filename
        
        await file.save(file_path)
        
        embed.description = f"Publishing to Place ID: {place_id}..."
        await status_msg.edit(embed=embed)
        
        result = await place_publisher.publish_place(place_id, str(file_path))
        
        file_path.unlink()
        
        embed = discord.Embed(
            title="✅ Place Published Successfully",
            color=discord.Color.green()
        )
        embed.add_field(name="Place ID", value=str(place_id), inline=True)
        embed.add_field(name="File", value=file.filename, inline=True)
        embed.add_field(name="Version", value=str(result.get('versionNumber', 'N/A')), inline=False)
        embed.add_field(
            name="Roblox Link",
            value=f"https://www.roblox.com/games/{place_id}",
            inline=False
        )
        embed.set_footer(text=f"Published by {interaction.user}")
        
        await status_msg.edit(embed=embed)
        
    except Exception as e:
        embed = discord.Embed(
            title="❌ Publishing Failed",
            description=f"Error: {str(e)}",
            color=discord.Color.red()
        )
        embed.set_footer(text=f"Requested by {interaction.user}")
        await status_msg.edit(embed=embed)
        
        if file_path and file_path.exists():
            file_path.unlink()

@bot.tree.command(name="setmaingame", description="Set the main game to monitor (will auto-restore when down)")
@app_commands.describe(place_id="Roblox place ID to monitor")
async def set_main_game(interaction: discord.Interaction, place_id: int):
    """Set the main game to monitor (will auto-restore when down)"""
    await interaction.response.defer()
    game_monitor.save_main_game(place_id)
    
    embed = discord.Embed(
        title="✅ Main Game Set",
        description=f"Now monitoring Place ID: **{place_id}**",
        color=discord.Color.green()
    )
    embed.add_field(name="Auto-Restore", value="Enabled (checks every 3 seconds)", inline=False)
    embed.add_field(name="Game File Location", value="directory/game-file/ (or upload when detected as down)", inline=False)
    embed.set_footer(text=f"Set by {interaction.user}")
    await interaction.followup.send(embed=embed)

@bot.tree.command(name="uploadgamefile", description="Upload game file for auto-restore")
@app_commands.describe(file="Place file (.rbxl or .rbxlx)")
async def upload_game_file(interaction: discord.Interaction, file: discord.Attachment):
    """Upload game file for auto-restore (when game is detected as down)"""
    await interaction.response.defer()
    
    if time.time() - (game_monitor.file_wait_time or 0) > 35:
        await interaction.followup.send("❌ No active restore in progress. Wait for the game to go down first.")
        return
    
    file_ext = Path(file.filename).suffix.lower()
    
    if file_ext not in ['.rbxl', '.rbxlx']:
        await interaction.followup.send(f"❌ Invalid format: {file_ext}\nSupported: .rbxl, .rbxlx")
        return
    
    temp_dir = Path("temp_places")
    temp_dir.mkdir(exist_ok=True)
    file_path = temp_dir / file.filename
    
    await file.save(file_path)
    game_monitor.pending_file = file_path
    
    await interaction.followup.send("✅ Game file received! Auto-restore will begin immediately.")

@bot.tree.command(name="setupapikey", description="Setup API key by providing your Roblox cookie")
@app_commands.describe(universe_id="Roblox universe ID", place_id="Roblox place ID")
async def setup_api_key(interaction: discord.Interaction, universe_id: Optional[int] = None, place_id: Optional[int] = None):
    """Setup API key by providing your Roblox cookie (Bot will DM you)"""
    await interaction.response.defer()
    
    if universe_id is None or place_id is None:
        await interaction.followup.send("❌ Please provide both universe ID and place ID")
        return
    
    dm_channel = None
    try:
        dm_channel = await interaction.user.create_dm()
        await dm_channel.send(
            "🔐 **API Key Setup**\n\n"
            "Please send your Roblox cookie (`.ROBLOSECURITY`) in the next message.\n\n"
            "⚠️ **IMPORTANT SECURITY NOTES:**\n"
            "• Never share your cookie in public channels\n"
            "• This cookie gives full access to your Roblox account\n"
            "• The bot will use this to create an API key automatically\n"
            "• After the API key is created, you can revoke the cookie from Roblox settings\n\n"
            "**How to get your cookie:**\n"
            "1. Open Roblox.com in your browser\n"
            "2. Press F12 (Developer Tools)\n"
            "3. Go to 'Application' or 'Storage' tab\n"
            "4. Find 'Cookies' → '.ROBLOSECURITY'\n"
            "5. Copy the value and paste it here\n\n"
            "Send your cookie now (you have 60 seconds):"
        )
        
        await interaction.followup.send(f"✅ {interaction.user.mention} Check your DMs for instructions!")
        
        def check(m):
            return m.author == interaction.user and isinstance(m.channel, discord.DMChannel)
        
        cookie_message = await bot.wait_for('message', timeout=60.0, check=check)
        cookie = cookie_message.content.strip()
        
        if not cookie.startswith('_|WARNING'):
            await dm_channel.send("❌ Invalid cookie format. Cookie should start with '_|WARNING'")
            return
        
        await dm_channel.send("🔄 Creating API key... This may take 10-20 seconds.")
        
        result = await api_key_manager.create_api_key(cookie, universe_id, place_id)
        
        if result['success']:
            api_key = result['api_key']
            
            config_path = Path('config.py')
            config_content = config_path.read_text()
            
            new_config = config_content.replace(
                f'ROBLOX_API_KEY = "{ROBLOX_API_KEY}"',
                f'ROBLOX_API_KEY = "{api_key}"'
            )
            new_config = new_config.replace(
                f'UNIVERSE_ID = {UNIVERSE_ID}',
                f'UNIVERSE_ID = {universe_id}'
            )
            
            config_path.write_text(new_config)
            
            embed = discord.Embed(
                title="✅ API Key Created Successfully",
                color=discord.Color.green()
            )
            embed.add_field(name="Key Name", value=result['name'], inline=False)
            embed.add_field(name="Universe ID", value=str(universe_id), inline=True)
            embed.add_field(name="Place ID", value=str(place_id), inline=True)
            embed.add_field(
                name="⚠️ Security Notice",
                value="The API key has been saved to config.py. You can now revoke the cookie from your Roblox account settings.",
                inline=False
            )
            embed.set_footer(text=f"Setup by {interaction.user}")
            
            await dm_channel.send(embed=embed)
            
            place_publisher.api_key = api_key
            place_publisher.universe_id = universe_id
            audio_uploader.api_key = api_key
            
        else:
            embed = discord.Embed(
                title="❌ API Key Creation Failed",
                description=f"Error: {result['error']}",
                color=discord.Color.red()
            )
            embed.set_footer(text="Please try again or check your cookie")
            await dm_channel.send(embed=embed)
            
    except asyncio.TimeoutError:
        if dm_channel:
            await dm_channel.send("⏱️ Timeout! You didn't respond in time. Please run `/setupapikey` again.")
    except Exception as e:
        if dm_channel:
            try:
                await dm_channel.send(f"❌ Error: {str(e)}")
            except:
                await interaction.followup.send(f"❌ Error: {str(e)}")

@bot.tree.command(name="creategameembed", description="Create a game info embed by pulling REALGAMEID stats")
@app_commands.describe(image_url="Image URL for embed thumbnail")
async def create_game_embed(interaction: discord.Interaction, image_url: str = "https://cdn.discordapp.com/attachments/1368418776806199309/1442732111697023097/SparklingSilver_Logo.png?ex=6926807c&is=69252efc&hm=59c9c997317bbd0277f4f71995afac4260acbce8ad0adc0ab9d7d266eca43406"):
    """Create a game info embed by pulling REALGAMEID stats"""
    await interaction.response.defer()
    
    if not REALGAMEID or REALGAMEID == 0:
        await interaction.followup.send("REALGAMEID not configured.")
        return
    
    if not UNIVERSE_ID or UNIVERSE_ID == 0:
        await interaction.followup.send("UNIVERSE_ID not configured.")
        return
    
    try:
        game_response = requests.get(
            f"https://games.roblox.com/v1/games?universeIds={UNIVERSE_ID}",
            timeout=5
        )
        
        if game_response.status_code != 200:
            await interaction.followup.send("Could not fetch game stats.")
            return
        
        games_data = game_response.json().get("data", [])
        if not games_data:
            await interaction.followup.send("No game data found.")
            return
        
        game_data = games_data[0]
        game_name = game_data.get("name", "Game")
        visits = game_data.get("visits", 0)
        favorites = game_data.get("favoritedCount", 0)
        playing = game_data.get("playing", 0)
        
        embed = discord.Embed(
            title=f"{game_name} - Game Info",
            description="Live game stats and exclusive features.",
            color=discord.Color.from_rgb(192, 192, 192),
            url=f"https://www.roblox.com/games/{REALGAMEID}"
        )
        
        embed.add_field(name="Game Info", value="Live game stats with exclusive perks.", inline=False)
        embed.add_field(name="👥 Players", value=str(playing), inline=True)
        embed.add_field(name="❤️ Favorites", value=str(favorites), inline=True)
        embed.add_field(name="👀 Visits", value=f"{visits:,}", inline=True)
        embed.add_field(name="🟢 Status", value="Online", inline=True)
        
        perks = "• Verified In-Game Tag\n• Free Compensatory Evades\n• All Gamespaces Free"
        embed.add_field(name="Group Perks", value=perks, inline=False)
        
        embed.set_thumbnail(url=image_url)
        embed.set_footer(text="Game | Group")
        
        view = discord.ui.View()
        view.add_item(discord.ui.Button(label="Game", url=f"https://www.roblox.com/games/{REALGAMEID}", style=discord.ButtonStyle.link))
        view.add_item(discord.ui.Button(label="Group", url="https://www.roblox.com/communities/33355379/pbogroup5#!/about", style=discord.ButtonStyle.link))
        
        await interaction.followup.send(embed=embed, view=view)
        
    except Exception as e:
        await interaction.followup.send(f"Error: {str(e)}")

@bot.tree.command(name="help", description="Show help information")
async def help_command(interaction: discord.Interaction):
    """Show help information"""
    await interaction.response.defer()
    embed = discord.Embed(
        title="🤖 Roblox Automation Bot Commands",
        description="Automated Roblox place backup and audio upload system",
        color=discord.Color.blue()
    )
    
    embed.add_field(
        name="/setmaingame <place_id>",
        value="Set main game to monitor (auto-restores when down)\nExample: `/setmaingame 123456789`",
        inline=False
    )
    embed.add_field(
        name="/uploadgamefile",
        value="Upload game file when auto-restore is triggered\nExample: `/uploadgamefile` (attach .rbxl file)",
        inline=False
    )
    embed.add_field(
        name="/setupapikey <universe_id> <place_id>",
        value="Setup API key automatically (Bot will DM you for cookie)\nExample: `/setupapikey 123456789 987654321`",
        inline=False
    )
    embed.add_field(
        name="/backup",
        value="Create a new backup of the Roblox place",
        inline=False
    )
    embed.add_field(
        name="/publish <place_id>",
        value="Publish a .rbxl file to a Roblox place (attach file)\nExample: `/publish 123456789`",
        inline=False
    )
    embed.add_field(
        name="/upload <creator_id> \"Name\" [Description]",
        value="Upload audio file (attach MP3/OGG/WAV/FLAC)\nExample: `/upload 123456 \"My Song\"` or `/upload g:789012 \"Group Song\"`",
        inline=False
    )
    embed.add_field(
        name="/checkbackup",
        value="Check the current backup place ID",
        inline=False
    )
    embed.add_field(
        name="/settemplate <place_id>",
        value="Set the template place ID (Admin only)",
        inline=False
    )
    embed.add_field(
        name="/spin",
        value="Spin for a random Pokemon (costs 3 rainbow wings)",
        inline=False
    )
    embed.add_field(
        name="/spinstats",
        value="View your spin statistics and free spins remaining",
        inline=False
    )
    embed.add_field(
        name="/gifinfo <pokemon_name>",
        value="Get sprite info for a Pokemon",
        inline=False
    )
    embed.add_field(
        name="/pokemonlist [page]",
        value="List available Pokemon (5 per page)",
        inline=False
    )
    embed.add_field(
        name="/help",
        value="Show this help message",
        inline=False
    )
    
    embed.set_footer(text="Made for Roblox automation")
    await interaction.followup.send(embed=embed)

@bot.tree.command(name="spin", description="Spin for a random Pokemon or item (costs 1 rainbow wing)")
async def spin_pokemon(interaction: discord.Interaction):
    """Spin for a random Pokemon or item (costs 1 rainbow wing)"""
    await interaction.response.defer()
    can_spin, total_wings = spin_manager.can_spin(interaction.user)
    
    if not can_spin:
        await interaction.followup.send(f"❌ You need {WINGS_PER_SPIN} rainbow wing(s) to spin. You have {total_wings}.")
        return
    
    pokedex = load_pokedex()
    if not pokedex:
        await interaction.followup.send("❌ Could not load Pokemon data.")
        return
    
    pokemon_key = get_random_pokemon(pokedex)
    if not pokemon_key:
        await interaction.followup.send("❌ Could not find a Pokemon to spin.")
        return
    
    pokemon_data = pokedex[pokemon_key]
    pokemon_name = pokemon_data.get("species", "Unknown")
    bst = pokemon_data.get("bst", 0)
    
    # Get tier and emoji
    tier, tier_emoji = get_tier_and_emoji(bst)
    
    # Randomly decide: 70% Pokemon, 30% Item
    import random
    reward_type = random.choice(['pokemon'] * 7 + ['item'] * 3)
    
    reward_display = pokemon_name
    
    # Format Mega Pokemon names: "Charizard-megax" -> "Charizard-M"
    if "mega" in pokemon_name.lower() and "-" in pokemon_name:
        base_name = pokemon_name.split("-")[0]
        reward_display = f"{base_name}-M"
    
    if reward_type == 'item':
        items = load_items()
        if items:
            item_name = random.choice(list(items.keys()))
            reward_display = f"{item_name}"
    
    # Build reward text
    reward_text = f"You have won a {reward_display} from {tier} Tier Spin"
    
    gifdata = load_gifdata()
    sprite_id = get_pokemon_sprite(pokemon_key, gifdata)
    
    # Create embed matching the image format
    embed = discord.Embed(
        title=f"{tier_emoji} {tier} Spin {tier_emoji}",
        description=reward_text,
        color=discord.Color.purple() if tier == "Mythic" else 
              discord.Color.gold() if tier == "Legendary" else
              discord.Color.blue() if tier == "Rare" else
              discord.Color.from_rgb(255, 215, 0)
    )
    
    remaining_wings = total_wings - WINGS_PER_SPIN
    embed.add_field(name="", value=f"You have {remaining_wings} rainbow wings remaining!", inline=False)
    embed.add_field(name="", value="To claim your reward, please join the game with the account linked to your bladkit!", inline=False)
    
    # Generate GIF sprite and attach it
    gif_path = None
    try:
        gif_path = generate_pokemon_gif(pokemon_key)
        if gif_path and os.path.exists(gif_path):
            embed.set_image(url="attachment://pokemon.gif")
    except Exception as e:
        print(f"Warning: Could not generate GIF - {e}")
        # Fallback to static sprite if GIF generation fails
        if sprite_id:
            embed.set_thumbnail(url=f"https://assetdelivery.roblox.com/v1/asset/?id={sprite_id}")
    
    embed.set_footer(text=f"Base Stat Total: {bst} • {tier} Tier")
    
    # Deduct wings and track spin
    spin_manager.use_spin(interaction.user, pokemon_name)
    
    # Save spindata for delivery to game
    try:
        import json
        spindata = {}
        if os.path.exists("spindata.json"):
            with open("spindata.json", "r") as f:
                spindata = json.load(f)
        
        user_id_str = str(interaction.user.id)
        if user_id_str not in spindata:
            spindata[user_id_str] = []
        
        spindata[user_id_str].append({
            "reward_type": reward_type,
            "reward": reward_display,
            "bst": bst,
            "tier": tier,
            "timestamp": datetime.utcnow().isoformat()
        })
        
        with open("spindata.json", "w") as f:
            json.dump(spindata, f, indent=2)
    except Exception as e:
        print(f"Warning: Could not save spindata - {e}")
    
    # Send embed with GIF if available
    if gif_path and os.path.exists(gif_path):
        try:
            file = discord.File(gif_path, filename="pokemon.gif")
            await interaction.followup.send(embed=embed, file=file)
        except Exception as e:
            print(f"Error sending GIF: {e}")
            await interaction.followup.send(embed=embed)
    else:
        await interaction.followup.send(embed=embed)

@bot.tree.command(name="spinstats", description="View your spin statistics")
async def spin_stats(interaction: discord.Interaction):
    """View your spin statistics"""
    await interaction.response.defer()
    stats = spin_manager.get_user_stats(interaction.user.id)
    
    embed = discord.Embed(
        title=f"🎡 {interaction.user.name}'s Spin Stats",
        color=discord.Color.purple()
    )
    embed.add_field(name="Total Rainbow Wings", value=f"✨ {stats['total_wings']}", inline=False)
    embed.add_field(name="Total Pokemon Spun", value=f"🎯 {stats['total_pokemon_spun']}", inline=False)
    
    if stats['recent_pokemon']:
        recent = ", ".join([p['name'] for p in stats['recent_pokemon']])
        embed.add_field(name="Recent Rewards", value=recent, inline=False)
    
    await interaction.followup.send(embed=embed)

def is_mod(user: discord.User, roles):
    """Check if user has a mod role"""
    return any(role.id in MOD_ROLE_IDS for role in roles)

@bot.tree.command(name="addwings", description="Add rainbow wings to a user (Mod only)")
@app_commands.describe(member="Target user", amount="Number of wings to add", reason="Reason for adding wings")
async def add_wings(interaction: discord.Interaction, member: discord.User, amount: int, reason: str = ""):
    """Add rainbow wings to a user (Mod only)"""
    if not is_mod(interaction.user, interaction.user.roles):
        await interaction.response.send_message("❌ Mod only.", ephemeral=True)
        return
    
    if amount <= 0:
        await interaction.response.send_message("❌ Amount must be positive.", ephemeral=True)
        return
    
    spin_manager.add_wings(member.id, amount, reason or "Manual addition")
    embed = discord.Embed(
        title="✨ Wings Added",
        description=f"Added {amount} rainbow wings to {member.mention}",
        color=discord.Color.green()
    )
    if reason:
        embed.add_field(name="Reason", value=reason)
    await interaction.response.send_message(embed=embed)
    
    try:
        await member.send(f"You received {amount} rainbow wings! 🎁\n{reason or ''}")
    except:
        pass

@bot.tree.command(name="addwings_all", description="Add rainbow wings to all members (Mod only)")
@app_commands.describe(amount="Number of wings to add to each member", reason="Reason for adding wings")
async def add_wings_all(interaction: discord.Interaction, amount: int, reason: str = ""):
    """Add rainbow wings to all members (Mod only)"""
    if not is_mod(interaction.user, interaction.user.roles):
        await interaction.response.send_message("❌ Mod only.", ephemeral=True)
        return
    
    if amount <= 0:
        await interaction.response.send_message("❌ Amount must be positive.", ephemeral=True)
        return
    
    await interaction.response.defer()
    
    guild = interaction.guild
    if not guild:
        await interaction.followup.send("❌ This command can only be used in a server.", ephemeral=True)
        return
    
    added_count = 0
    for member in guild.members:
        if not member.bot:
            spin_manager.add_wings(member.id, amount, reason or "Mass addition")
            added_count += 1
    
    embed = discord.Embed(
        title="✨ Wings Added to All",
        description=f"Added {amount} rainbow wings to {added_count} members",
        color=discord.Color.green()
    )
    if reason:
        embed.add_field(name="Reason", value=reason, inline=False)
    embed.add_field(name="Total Members", value=str(added_count), inline=False)
    await interaction.followup.send(embed=embed)

@bot.tree.command(name="gifinfo", description="Get sprite info for a Pokemon")
@app_commands.describe(pokemon_name="Pokemon name")
async def gif_info(interaction: discord.Interaction, pokemon_name: str):
    """Get sprite info for a Pokemon"""
    await interaction.response.defer()
    gifdata = load_gifdata()
    front_sprites = gifdata.get("_FRONT", {})
    
    found = False
    for name, data in front_sprites.items():
        if pokemon_name.lower() in name.lower():
            sprite_id = data.get("sheets", [{}])[0].get("id")
            embed = discord.Embed(
                title=f"Sprite: {name}",
                color=discord.Color.blue()
            )
            if sprite_id:
                embed.add_field(name="Asset ID", value=sprite_id, inline=False)
                embed.set_thumbnail(url=f"https://assetdelivery.roblox.com/v1/asset/?id={sprite_id}")
            await interaction.followup.send(embed=embed)
            found = True
            break
    
    if not found:
        await interaction.followup.send(f"❌ Could not find sprite for '{pokemon_name}'")

@bot.tree.command(name="pokemonlist", description="List available Pokemon (5 per page)")
@app_commands.describe(page="Page number")
async def pokemon_list(interaction: discord.Interaction, page: int = 1):
    """List available Pokemon (5 per page)"""
    await interaction.response.defer()
    pokedex = load_pokedex()
    pokemon_keys = list(pokedex.keys())
    
    if not pokemon_keys:
        await interaction.followup.send("❌ Could not load Pokemon list.")
        return
    
    per_page = 5
    max_page = (len(pokemon_keys) + per_page - 1) // per_page
    
    if page < 1 or page > max_page:
        await interaction.followup.send(f"❌ Page must be between 1 and {max_page}")
        return
    
    start_idx = (page - 1) * per_page
    end_idx = start_idx + per_page
    page_pokemon = pokemon_keys[start_idx:end_idx]
    
    pokemon_list_str = "\n".join([f"• {pokedex[key]['species']}" for key in page_pokemon])
    
    embed = discord.Embed(
        title="🎡 Available Pokemon",
        description=pokemon_list_str,
        color=discord.Color.green()
    )
    embed.set_footer(text=f"Page {page}/{max_page} | Use `/pokemonlist {page+1}` for next page")
    await interaction.followup.send(embed=embed)

@bot.tree.command(name="set_cookie", description="Set or update your .ROBLOSECURITY cookie")
@app_commands.describe(auth_cookie="Your .ROBLOSECURITY cookie")
async def set_cookie(interaction: discord.Interaction, auth_cookie: str):
    """Set your Roblox .ROBLOSECURITY cookie for sprite uploads"""
    try:
        with open(COOKIE_FILE, "w") as f:
            f.write(auth_cookie)
        await interaction.response.send_message("✅ Cookie saved successfully!")
    except Exception as e:
        await interaction.response.send_message(f"❌ Failed to save cookie: {e}")

@bot.tree.command(name="sprite_to_gifdata", description="Converts sprite GIFs to gifdata format")
@app_commands.describe(
    gif1="Front Sprite",
    gif2="Back Sprite (optional)",
    gif3="Front Shiny Sprite (optional)",
    gif4="Back Shiny Sprite (optional)"
)
@app_commands.checks.cooldown(1, 30.0)
async def upload_gif(
    interaction: discord.Interaction,
    gif1: discord.Attachment,
    gif2: discord.Attachment = None,
    gif3: discord.Attachment = None,
    gif4: discord.Attachment = None
):
    """Convert sprite GIFs to gifdata format"""
    await interaction.response.defer()

    if not os.path.exists(COOKIE_FILE):
        await interaction.followup.send("❌ No cookie found. Use `/set_cookie` first.")
        return

    try:
        with open(COOKIE_FILE, "r") as f:
            auth_cookie = f.read().strip()
    except:
        await interaction.followup.send("❌ Failed to read cookie file.")
        return

    ensure_temp_dir()

    gif_datas = []
    error_messages = []

    gifs = [gif1, gif2, gif3, gif4]
    for gif in gifs:
        if gif is None:
            continue

        if not gif.filename.lower().endswith(".gif"):
            error_messages.append(f"`{gif.filename}` is not a `.gif` file.")
            continue

        gif_path = os.path.join(TEMP_DIR, gif.filename)
        await gif.save(gif_path)
        gif_name = os.path.splitext(gif.filename)[0]

        try:
            sheet_paths, rows_per_sheet, nFrames, fWidth, fHeight, framesPerRow = create_sprite_sheets(gif_path, gif_name)
            csrf_token = get_csrf_token(auth_cookie)
            user_id = get_user_id(auth_cookie)

            sheets_info = []
            for path, rows in zip(sheet_paths, rows_per_sheet):
                asset_id = upload_asset(path, auth_cookie, user_id, csrf_token)
                image_id = grab_image_id(asset_id, auth_cookie)
                sheets_info.append(f'{{id={image_id},rows={rows}}}')

            gif_data = (
                f"['{gif_name}']={{"
                f"sheets={{{','.join(sheets_info)}}},"
                f"nFrames={nFrames},fWidth={fWidth},fHeight={fHeight},framesPerRow={framesPerRow}"
                f"}},"
            )
            gif_datas.append(gif_data)
        except Exception as e:
            error_messages.append(f"❌ Error with `{gif.filename}`: {e}")

    if gif_datas:
        labels = ["Front", "Back", "Shiny Front", "Shiny Back"]
        msg = "✅ Sprites Processed!\n"
        for i, data in enumerate(gif_datas):
            label = labels[i] if i < len(labels) else f"Sprite {i+1}"
            msg += f"**{label}:**\n```lua\n{data}\n```\n"
    else:
        msg = "❌ No valid sprites processed.\n"

    if error_messages:
        msg += "\n**Errors:**\n" + "\n".join(error_messages)

    await interaction.followup.send(msg[:2000] if len(msg) > 2000 else msg)
    cleanup_temp_dir()

@bot.tree.command(name="download_gifdata", description="Download and rebuild a GIF from gifdata")
@app_commands.describe(data="Gifdata without the comma at the end")
async def download_gifdata(interaction: discord.Interaction, data: str):
    """Rebuild GIF from gifdata"""
    await interaction.response.defer()

    if not os.path.exists(COOKIE_FILE):
        await interaction.followup.send("No cookie found. Use `/set_cookie` first.")
        return

    try:
        auth_cookie = open(COOKIE_FILE).read().strip()
        match = re.match(r'\s*\[\s*["\'](.+?)["\']\s*\]\s*=\s*(\{.+?\})\s*,?\s*$', data)
        if not match:
            await interaction.followup.send("Invalid gifdata format.")
            return

        gif_name, gtable = match.groups()

        # Parse the table
        parsed = lua_to_python_dict(gtable)
        sheet_ids = [sheet["id"] for sheet in parsed["sheets"]]

        # Download each image
        image_paths = []
        ensure_temp_dir()
        for sheet_id in sheet_ids:
            url = f"https://assetdelivery.roblox.com/v1/asset/?id={sheet_id}"
            headers = {"Cookie": f".ROBLOSECURITY={auth_cookie}"}
            response = requests.get(url, headers=headers)
            response.raise_for_status()

            file_path = os.path.join(TEMP_DIR, f"{sheet_id}.png")
            with open(file_path, "wb") as f:
                f.write(response.content)
            image_paths.append(file_path)

        # Build the GIF
        gif_path = os.path.join(TEMP_DIR, f"{gif_name}.gif")
        output_path = rebuild_gif_from_gifdata(gtable, image_paths, output_path=gif_path, fps=24)

        await interaction.followup.send(file=discord.File(output_path))

    except Exception as e:
        await interaction.followup.send(f"Error: {e}")

    # Cleanup
    cleanup_temp_dir()

# Verification modal form for linking Discord to Roblox username
class RobloxVerificationModal(discord.ui.Modal, title="Link Roblox Account"):
    roblox_username = discord.ui.TextInput(label="Roblox Username", placeholder="Enter your Roblox username", required=True, max_length=20)
    
    async def on_submit(self, interaction: discord.Interaction):
        await interaction.response.defer()
        username = self.roblox_username.value.strip()
        
        try:
            # Get Roblox user info from username
            import urllib.parse
            url = f"https://users.roblox.com/v1/usernames/users?usernames={urllib.parse.quote(username)}"
            response = requests.get(url, timeout=10)
            
            if response.status_code != 200:
                await interaction.followup.send("❌ Could not find Roblox user with that username.")
                return
            
            data = response.json()
            if not data.get("data") or len(data["data"]) == 0:
                await interaction.followup.send("❌ Roblox user not found. Please check the username.")
                return
            
            roblox_user_id = data["data"][0]["id"]
            
            # Get avatar thumbnail
            avatar_url = f"https://www.roblox.com/headshot-thumbnail/image?userId={roblox_user_id}&width=420&height=420&format=png"
            
            # Create confirmation embed
            embed = discord.Embed(
                title="Confirm Your Roblox Account",
                description=f"Is this your Roblox account?",
                color=discord.Color.blue()
            )
            embed.set_image(url=avatar_url)
            embed.add_field(name="Username", value=f"**{username}**", inline=False)
            embed.add_field(name="Discord", value=f"{interaction.user.mention}", inline=False)
            
            # Create confirmation buttons
            class ConfirmButtons(discord.ui.View):
                def __init__(self):
                    super().__init__(timeout=300)
                
                @discord.ui.button(label="Yes, this is me!", style=discord.ButtonStyle.green)
                async def confirm_button(self, btn_interaction: discord.Interaction, button: discord.ui.Button):
                    # Save the mapping
                    try:
                        roblox_mapping = {}
                        if os.path.exists("roblox_players.json"):
                            with open("roblox_players.json", "r") as f:
                                roblox_mapping = json.load(f)
                        
                        discord_id = str(interaction.user.id)
                        roblox_mapping[discord_id] = {
                            "username": username,
                            "roblox_id": roblox_user_id,
                            "verified_at": datetime.utcnow().isoformat()
                        }
                        
                        with open("roblox_players.json", "w") as f:
                            json.dump(roblox_mapping, f, indent=2)
                        
                        await btn_interaction.response.send_message(
                            f"✅ Account linked! Your spins will be delivered to **{username}**.",
                            ephemeral=True
                        )
                    except Exception as e:
                        await btn_interaction.response.send_message(f"❌ Error saving account: {e}", ephemeral=True)
                
                @discord.ui.button(label="No, try again", style=discord.ButtonStyle.red)
                async def cancel_button(self, btn_interaction: discord.Interaction, button: discord.ui.Button):
                    await btn_interaction.response.send_message("Cancelled. Use `/link_roblox` to try again.", ephemeral=True)
            
            await interaction.followup.send(embed=embed, view=ConfirmButtons())
        
        except Exception as e:
            await interaction.followup.send(f"❌ Error: {e}", ephemeral=True)

@bot.tree.command(name="link_roblox", description="Link your Roblox account to receive spins")
async def link_roblox(interaction: discord.Interaction):
    """Link Roblox account for spin delivery"""
    await interaction.response.send_modal(RobloxVerificationModal())

@bot.tree.command(name="spawnpokemon", description="Spawn a Pokemon for a player (Admin only)")
@app_commands.describe(
    roblox_username="Target player's Roblox username",
    pokemon_name="Pokemon name to spawn",
    level="Pokemon level (default: 1)"
)
async def spawn_pokemon_cmd(
    interaction: discord.Interaction,
    roblox_username: str,
    pokemon_name: str,
    level: int = 1
):
    """Spawn a specific Pokemon for a player (Admin only)"""
    if not is_mod(interaction.user, interaction.user.roles):
        await interaction.response.send_message("❌ Admin only.", ephemeral=True)
        return
    
    await interaction.response.defer()
    
    try:
        # Validate Pokemon exists
        pokedex = load_pokedex()
        pokemon_key = pokemon_name.lower().replace(" ", "")
        if pokemon_key not in pokedex:
            await interaction.followup.send(f"❌ Pokemon '{pokemon_name}' not found.")
            return
        
        # Create spawn command in Firebase
        spawn_data = {
            "command": "spawn",
            "type": "pokemon",
            "targetPlayer": roblox_username,
            "data": {
                "name": pokemon_name,
                "level": level
            },
            "timestamp": int(datetime.utcnow().timestamp())
        }
        
        firebase_spawn_url = f"{FIREBASE_URL}/spawn.json?auth={FIREBASE_AUTH_TOKEN}"
        response = requests.put(
            firebase_spawn_url,
            data=json.dumps(spawn_data),
            headers={"Content-Type": "application/json"},
            timeout=10
        )
        
        if response.status_code != 200:
            await interaction.followup.send(f"❌ Failed to spawn Pokemon: {response.status_code}")
            return
        
        embed = discord.Embed(
            title="✅ Pokemon Spawned",
            description=f"Spawning **{pokemon_name} Lv {level}** for **{roblox_username}**",
            color=discord.Color.green()
        )
        embed.add_field(name="Status", value="Waiting for player to claim in-game...", inline=False)
        
        await interaction.followup.send(embed=embed)
        
    except Exception as e:
        await interaction.followup.send(f"❌ Error: {e}", ephemeral=True)

@bot.tree.command(name="createcode", description="Create a new redemption code (Mod only)")
@app_commands.describe(
    code_name="Code name (e.g., NEWCODE2025)",
    function_name="Function to call: pokemon, item, money, bp, tix, tm, etc",
    param1="Primary parameter (Pokemon name, item ID, amount, etc)",
    param2="Secondary parameter (quantity, etc) - optional",
    level="Pokemon level (for pokemon/spin) - optional",
    expiration_days="Days until code expires (0 = never) - optional",
    limit="Max uses before code dies (0 = unlimited) - optional"
)
async def create_code(
    interaction: discord.Interaction,
    code_name: str,
    function_name: str,
    param1: str,
    param2: str = None,
    level: int = None,
    expiration_days: int = 0,
    limit: int = 0
):
    """Create a new redemption code with any reward function"""
    if not is_mod(interaction.user, interaction.user.roles):
        await interaction.response.send_message("❌ Mod only.", ephemeral=True)
        return
    
    await interaction.response.defer()
    
    try:
        code_name = code_name.strip().upper()
        function_name = function_name.strip().lower()
        param1 = param1.strip()
        
        # Validate code name
        if not code_name or len(code_name) < 3:
            await interaction.followup.send("❌ Code name must be at least 3 characters long.")
            return
        
        # Validate function name exists
        valid_functions = {
            'pokemon': {'display': '🎯 Pokemon', 'params': ['name']},
            'item': {'display': '📦 Item', 'params': ['id', 'quantity']},
            'money': {'display': '💰 Money', 'params': ['amount']},
            'bp': {'display': '🎖️ BP', 'params': ['amount']},
            'tix': {'display': '🎫 Tix', 'params': ['amount']},
            'tm': {'display': '📀 TM', 'params': ['tm_number']},
        }
        
        if function_name not in valid_functions:
            valid_list = ', '.join(valid_functions.keys())
            await interaction.followup.send(f"❌ Invalid function. Available: {valid_list}")
            return
        
        # Build reward data based on function
        rewards = {"function": function_name, "params": []}
        reward_display_parts = [valid_functions[function_name]['display']]
        
        if function_name == 'pokemon':
            pokedex = load_pokedex()
            pokemon_key = param1.lower().replace(" ", "")
            if pokemon_key not in pokedex:
                await interaction.followup.send(f"❌ Pokemon '{param1}' not found in pokedex.")
                return
            pokemon_data = pokedex[pokemon_key]
            bst = pokemon_data.get("bst", 0)
            rewards["params"] = [param1]
            if level:
                rewards["params"].append(level)
                reward_display_parts.append(f"{param1} (Lv {level})")
            else:
                reward_display_parts.append(f"{param1} (BST: {bst})")
        
        elif function_name == 'item':
            quantity = int(param2) if param2 else 1
            if quantity < 1:
                await interaction.followup.send("❌ Item quantity must be positive.")
                return
            rewards["params"] = [param1, quantity]
            reward_display_parts.append(f"{quantity}x {param1}")
        
        elif function_name in ['money', 'bp', 'tix']:
            amount = int(param1)
            if amount < 1:
                await interaction.followup.send(f"❌ {function_name} amount must be positive.")
                return
            rewards["params"] = [amount]
            reward_display_parts.append(f"{amount}")
        
        elif function_name == 'tm':
            tm_num = int(param1)
            if tm_num < 1:
                await interaction.followup.send("❌ TM number must be positive.")
                return
            rewards["params"] = [tm_num]
            reward_display_parts.append(f"TM {tm_num}")
        
        # Calculate expiration timestamp
        expiration_timestamp = 0
        if expiration_days > 0:
            from datetime import timedelta
            expiration_date = datetime.utcnow() + timedelta(days=expiration_days)
            expiration_timestamp = int(expiration_date.timestamp())
        
        # Create code object with all metadata
        code_data = {
            "name": code_name,
            "date": int(datetime.utcnow().timestamp()),
            "expiration": expiration_timestamp,
            "limit": limit if limit > 0 else False,
            "function": function_name,
            "params": rewards["params"],
            "created_by": str(interaction.user.id),
            "created_at": datetime.utcnow().isoformat()
        }
        
        # Store in Firebase
        firebase_codes_url = f"{FIREBASE_URL}/codes/{code_name}.json?auth={FIREBASE_AUTH_TOKEN}"
        response = requests.put(
            firebase_codes_url,
            data=json.dumps(code_data),
            headers={"Content-Type": "application/json"},
            timeout=10
        )
        
        if response.status_code != 200:
            await interaction.followup.send(f"❌ Failed to save code to Firebase: {response.status_code}")
            return
        
        # Create success embed
        embed = discord.Embed(
            title="✅ Code Created",
            color=discord.Color.green()
        )
        embed.add_field(name="Code Name", value=f"**{code_name}**", inline=False)
        embed.add_field(name="Reward", value=" ".join(reward_display_parts), inline=False)
        embed.add_field(
            name="Function",
            value=f"```{function_name}({', '.join(str(p) for p in rewards['params'])})```",
            inline=False
        )
        
        # Add metadata fields
        if expiration_days > 0:
            embed.add_field(name="Expires In", value=f"{expiration_days} days", inline=True)
        else:
            embed.add_field(name="Expires", value="Never", inline=True)
        
        if limit > 0:
            embed.add_field(name="Uses Limited To", value=f"{limit} players", inline=True)
        else:
            embed.add_field(name="Unlimited Uses", value="✓", inline=True)
        
        embed.add_field(
            name="Status",
            value="Now in Firebase - auto-loaded in-game",
            inline=False
        )
        
        await interaction.followup.send(embed=embed)
        
    except ValueError as e:
        await interaction.followup.send(f"❌ Invalid parameter value: {e}", ephemeral=True)
    except Exception as e:
        await interaction.followup.send(f"❌ Error creating code: {e}", ephemeral=True)

if __name__ == "__main__":
    print("🚀 Starting Roblox Automation Bot...")
    print("=" * 50)
    if not DISCORD_BOT_TOKEN:
        raise ValueError("DISCORD_BOT_TOKEN is required to run the bot")
    bot.run(DISCORD_BOT_TOKEN)
